Resources page
nditcommunity/ndit-website pull request #77
Opened 2024-11-15 07:19 UTC by galactic-src

# Add page - "Resources"

## Description

Add Resources page to the nav and show list of resources links as per the issue

[[link to ticket on issue board](https://github.com/nditcommunity/nditcommunity.github.io/issues/24)]

## Type of change

New feature

## Change log

- Added Resources item to navbar
- Added Resources.html to show categorised lists of links  

Is this the best place in the nav bar for this item?

Do we want the links displayed as list items?

We could do something cuter/slicker for the member-made things. Little chips with a coloured background? Could be a class which applies a `::after` for example, or in a <label>`.
Maybe simplest is best for accessibility for now though.

## Testing

Opened the page, tried each link.
Tried navigating to and from the page, via the nav.

## Checklist

- [X] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generate no new console warnings.
- [XI manually tested to prove my fix is effective or that my feature works.
- [ ] I have assigned this PR to an [owner](https://github.com/nditcommunity/ndit-website).

2024-11-15 07:51 UTC, galactic-src commented
For accessibility we could consider some styling to pick out links - at the moment they look a lot like text in dark mode. (Ideally not reliant solely on colour)

We could also consider a `:hover:` style to hint that they can be interacted with.

2024-11-15 20:37 UTC, hayleyw7 commented
On hold until this one is merged into main: https://github.com/nditcommunity/nditcommunity.github.io/pull/67.

2024-11-15 23:11 UTC, hayleyw7 requested changes
I just merged main into this branch so it's up-to-date with the big changes. I think it's a great start, but we may want to chat more about how exactly we want it to look and function, as well as whether or not we want it available on first launch (or add it later). Let's hold and chat?

2024-11-24 21:35 UTC, galactic-src commented
Definitely needs a better colour for dark mode link text :scream:
But I know you had potentially bigger changes/designs to consider so won't worry about it right now.

2026-07-30 22:28 UTC, hayleyw7 commented
Closing due to doing total revamp with AI.

2026-07-30 22:28 UTC, closed without merging